### ISSUE TITLE
[БАГ] Вызов функций без старта клиента

### ISSUE THREAD

**Issue by odi1n** [Damego/anilibria.py#5]
**Опишите баг**
Может быть я что-то не так делаю, но очень вряд-ли. Нужно вызвать функцию синхронно и в этот момент возникает ошибка.

**Воспроизведение бага**
Шаги, чтобы воспроизвести баг:
1. Вызываем синхронно
```python
async def test():
    client = AniLibriaClient()
    title = await client.get_random_title()
    print(title.description)
asyncio.run(test())
```
4. Увидеть ошибку
> Traceback (most recent call last):
  File "D:\MyProject\Python\2.Create\smotratv\content\tasks\tests.py", line 38, in <module>
    asyncio.run(test())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\MyProject\Python\2.Create\smotratv\content\tasks\tests.py", line 34, in test
    title = await client.get_random_title()
  File "D:\MyProject\Python\2.Create\smotratv\venv\lib\site-packages\anilibria\client\client.py", line 319, in get_random_title
    data = await self._http.v2.get_random_title(
  File "D:\MyProject\Python\2.Create\smotratv\venv\lib\site-packages\anilibria\api\http\v2.py", line 218, in get_random_title
    return await self.request.request("GET", f"{URL}/getRandomTitle", payload)
  File "D:\MyProject\Python\2.Create\smotratv\venv\lib\site-packages\anilibria\api\http\request.py", line 38, in request
    async with _session.request(method, url, params=data, **kwargs) as response:
  File "D:\MyProject\Python\2.Create\smotratv\venv\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "D:\MyProject\Python\2.Create\smotratv\venv\lib\site-packages\aiohttp\client.py", line 466, in _request
    with timer:
  File "D:\MyProject\Python\2.Create\smotratv\venv\lib\site-packages\aiohttp\helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000122FD7AA4C0>

**Ожидаемое поведение**
Ожидал что метод отработает синхронно

**Дополнительная информация**
Библиотеки имеет большой функционал это очень хорошо, спасибо)

**Comment by Damego** [comment]
Спасибо! Извини, но на данный момент невозможно использовать методы клиента, без его непосредственного запуска через `client.start()`.
Это можно исправить, но на данный момент я нахожусь в другом городе и на руках только телефон. Я оставлю этот issue открытым, и сообщу, когда баг будет пофикшен. Примерное время ожидания 5-6 дней.

**Comment by Damego** [comment]
Создал пулл, можешь его установить и проверить работоспособность.
Из важного:
Так как открывается сессия, но в конце не закрывается, вылезает соответствующая ошибка, чтобы избавиться от неё используй `await client.close()`.
Если что-то работает не так или есть вопросы, спрашивай, если всё нормально, то я выкладываю новую версию.
